### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by jmessick9** [arskinner/Appcelerator-CardIO#1]
Are the CardIO files missing from the Xcode project. And is it possible to build this with the latest Ti. sdk 5.0+.

**Comment by arskinner** [comment]
Yeah, GitHub choked on the cardio library file because it's over 100mb. Going to try adding it as a submodule instead but in the meantime you can add the library and headers downloaded from their site: https://github.com/card-io/card.io-iOS-SDK

And it should be possible to build with 5.0+ -- I am using the latest version of the module template from 5.0.2.

**Comment by jmessick9** [comment]
Yeah, I tried that.  First i was missing the doc files etc when running build.by. figured that out. I added card.io(unzipping libCardIO.a.zip).

When i install the module then build my project i get this error:
Undefined symbols for architecture arm64:
[TRACE] :    "_OBJC_CLASS_$_CardIOPaymentViewController", referenced from:
[TRACE] :        objc-class-ref in libcom.likelysoft.cardio.a(ComLikelysoftCardioModule.o)
[TRACE] :    "_OBJC_CLASS_$_CardIOUtilities", referenced from:
[TRACE] :        objc-class-ref in libcom.likelysoft.cardio.a(ComLikelysoftCardioModule.o)
[TRACE] :  ld: symbol(s) not found for architecture arm64

I can't get this to work like expected. I am not an Xcode pro either.

**Comment by arskinner** [comment]
Admittedly I haven't tried re-downloading and re-building from the repository alone, so let me give that a shot and I'm sure I'll see what's missing.

**Comment by arskinner** [comment]
I added some more instructions to the README.md file and also added the CardIO headers to the project, and included them in the XCode project. All that remains should be to add the libCardIO.a file to the CardIO folder and to XCode. Then, run build.py

I also added a documentation folder so the build doesn't die trying to find it.

**Comment by ankesh27** [comment]
is it possible to build the module with 3.5.X SDK ?

**Comment by arskinner** [comment]
@ankesh27 I have not tried. You can certainly update the config files and give it a shot
